name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: clone submodules
      run: git submodule update --init

    - name: compile
      run: make -C src rmcios

    - name: make dir
      run: mkdir artifacts

    - name: copy
      run: copy RMCIOS.exe artifacts\
    - name: copy
      run: copy run_program.dll artifacts\
    - name: copy
      run: copy LICENSE artifacts\
    - name: copy
      run: Xcopy /E /I modules artifacts\modules\
    - name: copy
      run: Xcopy /E /I examples artifacts\examples\

    - uses: actions/upload-artifact@v1
      name: upload
      with:
        name: RMCIOS-binary
        path: artifacts   
 

